### ISSUE TITLE
Is there any possibility of integrating AO Smith geysers which work on AO Smith smart app?

### ISSUE THREAD

**Issue by g1r1** [bdr99/py-aosmith#1]
So,  I am considering buying this model

https://www.aosmithindia.com/product/water-heater/storage-water-heater/heatbot-wifi/

However, I noticed that it uses a different app 
https://play.google.com/store/apps/details?id=aosmithindia.comheat.bot

Can this be integrated? I tried using the same username password registered with the app on the HA integration and it does not work.

If it won't work, perhaps I need to find another water heater that could be supported in HA.

**Comment by bdr99** [comment]
Unfortunately, if the device doesn't work with the A. O. Smith app mentioned in the integration docs, it definitely won't work with this integration. I took a look at the app from your link above, and noticed that it is actually a rebranded Tuya app. This is a common way for smart home device manufacturers to get an app up and running quickly, and it means that Tuya devices all share a common API. There's a chance the device may work with the [Tuya integration](https://www.home-assistant.io/integrations/tuya/). The only way to test this would be to try to pair the device with the Tuya Smart or Smart Life apps.

**Comment by g1r1** [comment]
Thanks for the heads up, I do think it is using Tuya now that I looked at both the apps. Unfortunately, I have no way of testing that theory without buying one.  

Closing this issue and will report back if I do end up getting one.
