### ISSUE TITLE
r1.wh8.co down for days

### ISSUE THREAD

**Issue by lrehmann** [bdr99/py-aosmith#3]
I've found r2.wh8.co is up despite r1.wh8.co being down, breaking app functionality and this python script. 

It's mostly drop in replacement (just change the api endpoint domain), but hot water status seems to be on a scale up to 10.
'hotWaterStatus': 10
The interval is unclear to me right now, likely either 0 or 1. 

I've also had some success resolving r1.wh8.co to 52.20.96.188 (r2.wh8.co), but that presents a certificate issue.

**Comment by bdr99** [comment]
Thanks for raising this issue. When I have some time I'll work on updating this library accordingly.

**Comment by bdr99** [comment]
Regarding the changes to the `hotWaterStatus` you mentioned, I noticed that my reading from water heater is inverted from what I'd expect. In the app, it's showing as empty or 10% when the water is hot, and the percentage increases when I use the hot water. @lrehmann Is it the same for you?

**Comment by lrehmann** [comment]
Yes, I'm seeing similar data in the app. 

Currently showing 50% at my typical setpoint of 150°, changing it to 140° reduces availability to 40%, changing it to 130° reduces availability to 30%. 

It appears the app is now using r2.wh8.co instead of r1.wh8.co

Before the app updated to using r2, the availability seemed to stay more within reasonable parameters.

**Comment by bdr99** [comment]
This is fixed in version 1.0.9. I added logic to normalize the hot water status so that 100% indicates full hot water availability and 0% means no hot water left.
